name: Release

on:
  push:
    branches:
      - master
      - beta
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: yarn install

    - name: Build and verify ES2019 compatibility
      run: |
        yarn run build
        yarn run transpile-dist
        yarn run verify:es2019

    - name: Run Semantic Release
      run: npx semantic-release --debug
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
